name: Lighthouse
on: [pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Our Taskfile requires a proper checkout to function because of
          # certain vars.
          fetch-depth: 0
      - name: Install go-task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup site
        run: task ci:reset
      - name: Set local URL port as variable.
        run: echo "LOCAL_PORT=$(docker compose port varnish 8080 2>/dev/null | cut -d ":" -f2)" >> $GITHUB_ENV
      - name: Lighthouse Performance
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: 'http://localhost:${{ env.LOCAL_PORT }}'
          slackWebhookUrl: ${{ secrets.ZULIP_INCOMING_WEBHOOK_URL }}
